#启动服务端口
server: 
  port: 8001
#服务名称(服务注册到Eureka注册中心)
spring:
  application:
    name: zxf-lancoo-member
#服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:8200/eureka
     
#因为是注册中心，不会自己注册
    register-with-eureka: true
#是否需要从eureka上获取注册信息
    fetch-registry: true

    