#启动服务端口
server: 
  port: 8021
#服务名称(服务注册到Eureka注册中心)
spring:
  application:
    name: zxf-lancoo-order
#服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
     
#因为是注册中心，不会自己注册
    register-with-eureka: true
#是否需要从eureka上获取注册信息
    fetch-registry: true
    
###设置feign客户端超时时间
#springcloud feign默认开启支持ribbon
ribbon:
###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
 ReadTimeout: 5000
###指的是建立连接后从服务器读取到可用资源所用的时间。 
 ConnectTimeout: 5000

#服务降级hystrix
feign:
 hystrix:
  enabled: true
    
#### hystrix禁止服务超时时间
hystrix:  
 command: 
   default: 
      execution: 
       timeout: 
        enabled: false
      #最大并发请求数
      isolation: 
       semaphore: 
        maxConcurrentRequests: false
        #暂未测试有什么卵用
#       thread: 
#        timeoutInMillseconds: 7000
